services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "80:80"
    command: >
      sh -c "
      echo $CWD && /app/serve
      "